// Tailwind utilities migrated from the chat UI stylesheet.
export default {
  "chatWrap": "[display:flex] [flex-direction:column] [height:calc(100vh_-_25px)] [background:var(--color-bg)] [padding:0_200px] [font-family:inherit] [overflow-x:hidden]",
  "header": "[display:flex] [align-items:center] [gap:12px] [padding:30px_16px_0] [height:80px] [min-height:80px] [border-bottom:1px_solid_var(--color-border)] [background:var(--color-bg)] [box-shadow:0_1px_0_rgba(0,_0,_0,_0.1)] [z-index:1500] [position:relative] [flex-shrink:0]",
  "headerThumb": "[width:32px] [height:32px] [border-radius:50%] [display:flex] [align-items:center] [justify-content:center] [overflow:hidden] [flex-shrink:0]",
  "headerProfileButton": "[border:0] [padding:0] [background:transparent] [cursor:pointer]",
  "headerHashIcon": "[color:var(--color-text)] [opacity:0.5] [font-size:18px] [font-weight:700]",
  "headerName": "[font-size:15px] [font-weight:700] [color:var(--color-text)]",
  "headerDivider": "[width:1px] [height:24px] [background:var(--color-border)] [margin:0_4px]",
  "headerDesc": "[font-size:13px] [color:#888] [flex:1] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis]",
  "headerActions": "[display:flex] [align-items:center] [gap:4px] [margin-left:auto]",
  "headerIconBtn": "[background:none] [border:none] [cursor:pointer] [color:#888] [width:32px] [height:32px] [border-radius:4px] [display:flex] [align-items:center] [justify-content:center] [font-size:18px] [transition:background_0.15s,_color_0.15s]",
  "appointmentCard": "[display:grid] [grid-template-columns:minmax(0,_1.2fr)_minmax(280px,_1fr)_auto] [gap:14px] [align-items:center] [margin:12px_0_0] [padding:14px_16px] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-sidebar)] [color:var(--color-text)] [flex-shrink:0]",
  "appointmentCardMeta": "[min-width:0] [display:grid] [grid-template-columns:1.5fr_0.8fr_0.8fr] [gap:12px]",
  "appointmentCardMapBtn": "[height:36px] [padding:0_14px] [border:0] [border-radius:6px] [background:var(--color-active)] [color:white] [font-size:13px] [font-weight:800] [cursor:pointer] [white-space:nowrap]",
  "appointmentReminderBar": "[display:flex] [align-items:center] [gap:12px] [margin:12px_0_0] [padding:12px_14px] [border:1px_solid_color-mix(in_srgb,_var(--color-active)_45%,_var(--color-border))] [border-radius:8px] [background:color-mix(in_srgb,_var(--color-active)_12%,_var(--color-bg))] [color:var(--color-text)] [flex-shrink:0]",
  "appointmentReminderIcon": "[width:38px] [height:38px] [border-radius:8px] [background:var(--color-active)] [color:white] [display:flex] [align-items:center] [justify-content:center] [font-size:14px] [font-weight:900] [flex-shrink:0]",
  "appointmentReminderText": "[min-width:0] [flex:1] [display:flex] [flex-direction:column] [gap:3px]",
  "appointmentReminderAction": "[height:34px] [padding:0_12px] [border:0] [border-radius:6px] [background:var(--color-active)] [color:white] [font-size:13px] [font-weight:800] [cursor:pointer] [flex-shrink:0]",
  "messages": "[flex:1] [overflow-y:auto] [overflow-x:hidden] [padding:16px_0_8px] [display:flex] [flex-direction:column] [background:var(--color-bg)]",
  "dateDivider": "[display:flex] [align-items:center] [gap:8px] [padding:12px_8px] [margin:4px_0]",
  "dateDividerText": "[font-size:11px] [font-weight:600] [color:#888] [white-space:nowrap]",
  "systemMsg": "[text-align:center] [font-size:13px] [font-weight:500] [color:#888] [padding:4px_8px] [align-self:center] [margin:4px_0]",
  "systemMsgMap": "[width:100%] [max-width:764px] [margin:8px_auto_0]",
  "deletionWarningMsg": "[text-align:center] [font-size:13px] [font-weight:700] [color:#666] [background:#f0f0f0] [padding:8px_16px] [border-radius:8px] [margin:12px_auto] [width:fit-content] [max-width:80%] [border:1px_solid_#ddd]",
  "msgRow": "[display:flex] [flex-direction:row] [gap:0] [padding:2px_8px_2px_8px] [position:relative] [transition:background_0.05s]",
  "msgAvatarWrap": "[width:40px] [flex-shrink:0] [display:flex] [justify-content:center] [padding-top:2px]",
  "avatarWrapSmall": "[position:relative] [width:40px] [height:40px] [flex-shrink:0]",
  "avatarBorderSmall": "[position:absolute] [top:-25%] [left:-25%] [width:150%] [height:150%] [z-index:5] [pointer-events:none]",
  "msgAvatar": "[width:100%] [height:100%] [border-radius:50%] [background:gray] [display:flex] [align-items:center] [justify-content:center] [font-size:12px] [font-weight:700] [color:white] [flex-shrink:0] [overflow:hidden] [cursor:pointer]",
  "compactTime": "[font-size:10px] [color:transparent] [width:40px] [text-align:center] [padding-top:3px] [line-height:1.2]",
  "msgContent": "[flex:1] [min-width:0] [padding-left:12px]",
  "msgHeader": "[display:flex] [align-items:baseline] [gap:8px] [margin-bottom:2px]",
  "msgNickname": "[font-size:15px] [font-weight:600] [color:var(--color-text)] [cursor:pointer] [line-height:1.3]",
  "msgNicknameMine": "[color:var(--color-active)]",
  "msgHostBadge": "[display:inline-block] [background:var(--color-active,_#f39c12)] [color:#fff] [font-size:10px] [font-weight:700] [padding:1px_6px] [border-radius:8px] [margin-left:6px] [vertical-align:middle]",
  "msgTimestamp": "[font-size:11px] [color:#888] [font-weight:400]",
  "editedTag": "[font-size:10px] [color:#888] [font-style:italic] [margin-left:4px]",
  "msgBubble": "[font-size:15px] [line-height:1.5] [word-break:break-word] [color:var(--color-text)] [white-space:pre-wrap]",
  "pendingMessage": "[opacity:0.62]",
  "failedMessage": "[opacity:0.85] [color:#ef4444]",
  "attachmentWrap": "[display:inline-flex] [flex-direction:column] [gap:6px] [max-width:min(420px,_100%)]",
  "attachmentVideo": "[display:block] [max-width:100%] [max-height:320px] [border-radius:8px] [border:1px_solid_var(--color-border)] [background:#000]",
  "attachmentName": "[font-size:12px] [color:#888] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  "attachmentFileCard": "[display:flex] [align-items:center] [justify-content:space-between] [gap:16px] [width:min(360px,_100%)] [min-height:46px] [padding:10px_12px_10px_14px] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-input-bg)] [color:var(--color-text)] [font-size:13px] [font-weight:700] [text-decoration:none] [box-sizing:border-box] [transition:border-color_0.15s,_background_0.15s,_color_0.15s]",
  "attachmentFileName": "[min-width:0] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  "attachmentDownloadIcon": "[display:inline-flex] [align-items:center] [justify-content:center] [flex:0_0_auto] [width:30px] [height:30px] [border-radius:6px] [background:var(--color-sidebar)] [color:currentColor]",
  "messagePayload": "[display:flex] [flex-direction:column] [gap:8px]",
  "payloadText": "[white-space:pre-wrap]",
  "messageLink": "[color:var(--color-active)] [text-decoration:underline] [text-underline-offset:2px] [word-break:break-all]",
  "youtubePreview": "[display:flex] [gap:12px] [max-width:min(500px,_100%)] [min-height:96px] [padding:10px] [border:1px_solid_var(--color-border)] [border-radius:12px] [background:var(--color-input-bg)] [color:var(--color-text)] [text-decoration:none] [transition:border-color_0.15s,_background_0.15s,_transform_0.15s]",
  "linkPreview": "[display:flex] [gap:12px] [max-width:min(500px,_100%)] [min-height:96px] [padding:10px] [border:1px_solid_var(--color-border)] [border-radius:12px] [background:var(--color-input-bg)] [color:var(--color-text)] [text-decoration:none] [transition:border-color_0.15s,_background_0.15s,_transform_0.15s]",
  "sharedPostCard": "[flex-direction:column] [width:min(500px,_100%)] [min-height:auto] [overflow:hidden] [padding:0] [cursor:pointer] [text-align:left] [gap:0]",
  "sharedPostImageContainer": "[width:100%] [aspect-ratio:16_/_9] [overflow:hidden] [background-color:var(--color-border)] [display:flex] [justify-content:center] [align-items:center]",
  "sharedPostImage": "[width:100%] [height:100%] [display:block] [object-fit:cover]",
  "sharedPostContent": "[flex:1] [min-width:0] [display:flex] [flex-direction:column] [gap:4px] [padding:12px_14px_13px]",
  "sharedPostEyebrow": "[display:none]",
  "sharedPostTitle": "[font-size:16px] [line-height:1.35] [color:var(--color-text)] [overflow:hidden] [text-overflow:ellipsis] [display:-webkit-box] [-webkit-line-clamp:2] [-webkit-box-orient:vertical] [white-space:normal]",
  "sharedPostMeta": "[font-size:12px] [line-height:1.35] [color:var(--color-deactive)] [overflow:hidden] [text-overflow:ellipsis] [white-space:normal]",
  "youtubeThumb": "",
  "linkPreviewThumbSkeleton": "[background:linear-gradient(90deg,_transparent,_rgba(255,_255,_255,_0.18),_transparent),_var(--color-border)] [background-size:180%_100%] [animation:linkPreviewSkeleton_1.2s_ease-in-out_infinite]",
  "youtubePlayBadge": "[position:absolute] [inset:auto_auto_8px_8px] [width:28px] [height:28px] [border-radius:999px] [background:rgba(0,_0,_0,_0.72)] [color:#fff] [display:flex] [align-items:center] [justify-content:center] [font-size:11px] [font-weight:900]",
  "youtubeMeta": "[min-width:0] [display:flex] [flex-direction:column] [gap:6px] [justify-content:center]",
  "linkPreviewMeta": "[min-width:0] [display:flex] [flex-direction:column] [gap:6px] [justify-content:center]",
  "youtubeDomain": "[font-size:11px] [font-weight:800] [color:var(--color-active)] [text-transform:uppercase] [letter-spacing:0.2px] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  "youtubeTitle": "[font-size:14px] [line-height:1.4] [font-weight:800] [color:var(--color-text)] [display:-webkit-box] [-webkit-line-clamp:2] [-webkit-box-orient:vertical] [overflow:hidden]",
  "linkPreviewTitle": "[font-size:14px] [line-height:1.4] [font-weight:800] [color:var(--color-text)] [display:-webkit-box] [-webkit-line-clamp:2] [-webkit-box-orient:vertical] [overflow:hidden]",
  "linkPreviewSubtitle": "[font-size:12px] [line-height:1.35] [color:var(--color-text)] [opacity:0.72] [display:-webkit-box] [-webkit-line-clamp:1] [-webkit-box-orient:vertical] [overflow:hidden]",
  "linkPreviewIcon": "[width:128px] [min-width:128px] [aspect-ratio:16_/_9] [border-radius:12px] [display:flex] [align-items:center] [justify-content:center] [font-size:28px] [font-weight:900] [flex-shrink:0]",
  "linkPreviewUrl": "[font-size:11px] [color:var(--color-deactive)] [opacity:0.85] [overflow:hidden] [text-overflow:ellipsis] [white-space:nowrap]",
  "emojiOnly": "[display:inline-block] [font-size:42px] [line-height:1.15] [white-space:normal]",
  "payloadAttachments": "[display:flex] [flex-direction:column] [gap:10px]",
  "mediaGrid": "[display:grid] [grid-template-columns:repeat(2,_minmax(0,_180px))] [grid-auto-rows:132px] [gap:4px] [width:min(364px,_100%)] [overflow:hidden] [border-radius:8px]",
  "mediaGridSingle": "[display:block] [width:min(420px,_100%)]",
  "mediaGridTwo": "[grid-template-columns:repeat(2,_minmax(0,_180px))] [grid-auto-rows:180px]",
  "mediaGridItem": "[position:relative] [display:block] [min-width:0] [min-height:0] [overflow:hidden] [color:#fff] [background:transparent] [border:none] [padding:0] [cursor:pointer] [background:none]",
  "mediaOverflow": "[position:absolute] [inset:0] [display:flex] [align-items:center] [justify-content:center] [background:rgba(0,_0,_0,_0.55)] [font-size:26px] [font-weight:800]",
  "videoBadge": "[position:absolute] [left:8px] [bottom:8px] [padding:3px_7px] [border-radius:4px] [background:rgba(0,_0,_0,_0.68)] [color:#fff] [font-size:11px] [font-weight:700]",
  "mediaLightbox": "[position:fixed] [inset:0] [z-index:6000] [display:flex] [align-items:center] [justify-content:center] [background:rgba(0,_0,_0,_0.86)] [padding:56px] [box-sizing:border-box]",
  "lightboxBody": "[max-width:min(1100px,_100%)] [max-height:100%] [display:flex] [flex-direction:column] [gap:10px] [align-items:center]",
  "lightboxMeta": "[width:100%] [display:flex] [justify-content:space-between] [gap:16px] [color:#fff] [font-size:13px] [font-weight:700]",
  "lightboxClose": "[top:18px] [right:20px] [width:40px] [height:40px] [border-radius:8px] [font-size:30px] [line-height:1]",
  "lightboxNav": "[top:50%] [width:44px] [height:64px] [border-radius:8px] [font-size:48px] [transform:translateY(-50%)]",
  "lightboxDownloadActions": "[position:fixed] [top:18px] [right:72px] [display:flex] [gap:8px] [z-index:1]",
  "lightboxPrev": "[left:20px]",
  "lightboxNext": "[right:20px]",
  "fileGalleryOverlay": "[position:fixed] [inset:0] [z-index:5200] [display:flex] [align-items:center] [justify-content:center] [padding:32px] [background:rgba(0,_0,_0,_0.45)]",
  "fileGalleryPanel": "[width:min(760px,_100%)] [max-height:min(720px,_calc(100vh_-_64px))] [display:flex] [flex-direction:column] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-sidebar)] [color:var(--color-text)] [box-shadow:0_20px_60px_rgba(0,_0,_0,_0.28)] [overflow:hidden]",
  "fileGalleryHeader": "[display:flex] [align-items:center] [justify-content:space-between] [gap:16px] [padding:18px_20px] [border-bottom:1px_solid_var(--color-border)]",
  "fileGalleryBody": "[padding:18px_20px_22px] [overflow-y:auto]",
  "fileGalleryEmpty": "[padding:54px_20px] [color:var(--color-deactive)] [text-align:center] [font-size:14px]",
  "fileGallerySectionTitle": "[margin-bottom:10px] [font-size:13px] [font-weight:900] [color:var(--color-text)]",
  "fileGalleryMediaGrid": "[display:grid] [grid-template-columns:repeat(auto-fill,_minmax(132px,_1fr))] [gap:10px]",
  "fileGalleryMediaItem": "[min-width:0] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-input-bg)] [color:var(--color-text)] [text-decoration:none] [overflow:hidden] [padding:0] [cursor:pointer] [text-align:left]",
  "fileGalleryFileList": "[display:flex] [flex-direction:column] [gap:8px]",
  "fileGalleryFileItem": "[display:flex] [align-items:center] [gap:12px] [min-width:0] [padding:11px_12px] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-input-bg)] [color:var(--color-text)] [text-decoration:none]",
  "fileGalleryFileIcon": "[width:42px] [height:42px] [border-radius:8px] [background:var(--color-active)] [color:white] [display:flex] [align-items:center] [justify-content:center] [font-size:10px] [font-weight:900] [flex-shrink:0]",
  "fileGalleryFileInfo": "[min-width:0] [display:flex] [flex-direction:column] [gap:4px]",
  "deleted": "[color:#888] [font-style:italic]",
  "replyPreviewInMsg": "[display:flex] [align-items:center] [gap:6px] [padding:2px_8px] [margin-bottom:4px] [font-size:13px] [cursor:pointer] [background:var(--color-input-bg)] [border-radius:4px] [width:fit-content] [max-width:90%] [border-left:3px_solid_var(--color-active)] [transition:background_0.15s]",
  "replyAvatar": "[width:16px] [height:16px] [border-radius:50%] [background:var(--color-deactive)] [flex-shrink:0] [display:flex] [align-items:center] [justify-content:center] [overflow:hidden]",
  "replyName": "[font-weight:700] [color:var(--color-active)] [font-size:12px] [flex-shrink:0]",
  "replyContent": "[color:var(--color-text)] [opacity:0.7] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis] [font-size:12px]",
  "msgActions": "[position:absolute] [top:-16px] [right:8px] [display:flex] [align-items:center] [background:var(--color-bg)] [border:1px_solid_var(--color-border)] [border-radius:4px] [box-shadow:0_4px_8px_rgba(0,_0,_0,_0.2)] [z-index:200] [overflow:visible] [&>button]:[background:none] [&>button]:[border:none] [&>button]:[cursor:pointer] [&>button]:[padding:6px_8px] [&>button]:[font-size:16px] [&>button]:[display:flex] [&>button]:[align-items:center] [&>button]:[justify-content:center] [&>button]:[color:#888] [&>button]:[border-radius:3px] [&>button]:[position:relative] [&>button:hover]:[background:var(--color-input-bg)] [&>button:hover]:[color:var(--color-text)] [&>div>button]:[background:none] [&>div>button]:[border:none] [&>div>button]:[cursor:pointer] [&>div>button]:[padding:6px_8px] [&>div>button]:[font-size:16px] [&>div>button]:[display:flex] [&>div>button]:[align-items:center] [&>div>button]:[justify-content:center] [&>div>button]:[color:#888] [&>div>button]:[border-radius:3px] [&>div>button]:[position:relative] [&>div>button:hover]:[background:var(--color-input-bg)] [&>div>button:hover]:[color:var(--color-text)]",
  "quickReactions": "[display:flex]",
  "actionDivider": "[width:1px] [height:20px] [background:var(--color-border)] [margin:0_2px]",
  "emojiPickerPopup": "[position:absolute] [bottom:calc(100%_+_8px)] [right:0] [z-index:6000] [max-width:min(352px,_calc(100vw_-_28px))] [box-shadow:0_8px_24px_rgba(0,_0,_0,_0.3)] [border-radius:10px] [overflow:hidden] [animation:popIn_0.12s_ease-out] [transform-origin:bottom_right]",
  "reactionsArea": "[display:flex] [flex-wrap:wrap] [gap:4px] [margin-top:4px]",
  "reactionBadge": "[background:var(--color-input-bg)] [border:1px_solid_var(--color-border)] [padding:2px_8px] [border-radius:8px] [font-size:13px] [cursor:pointer] [display:flex] [align-items:center] [gap:5px] [transition:all_0.1s] [height:24px]",
  "reactionCount": "[font-size:12px] [font-weight:600] [color:var(--color-text)]",
  "activeReaction": "[background:var(--color-input-focus-bg)] [border-color:var(--color-active)]",
  "readCount": "[font-size:10px] [color:var(--color-active)] [font-weight:700] [margin-top:2px]",
  "highlight": "[animation:highlightMessage_2s_ease-out]",
  "inputContext": "[background:var(--color-input-bg)] [border-top:1px_solid_var(--color-border)] [padding:10px_8px_10px_12px] [display:flex] [justify-content:space-between] [align-items:center] [animation:slideUp_0.15s_ease-out] [flex-shrink:0] [margin:0_8px] [border-radius:8px_8px_0_0] [border:1px_solid_var(--color-border)] [border-bottom:none]",
  "closeBtn": "[background:none] [border:none] [cursor:pointer] [color:#888] [padding:4px] [border-radius:4px] [display:flex] [align-items:center] [justify-content:center] [flex-shrink:0] [font-size:20px] [line-height:1] hover:[color:var(--color-text)] hover:[background:var(--color-input-bg)]",
  "contextLabel": "[font-size:11px] [font-weight:700] [color:var(--color-active)] [display:flex] [align-items:center] [gap:6px] [margin-bottom:2px] [text-transform:uppercase] [letter-spacing:0.5px]",
  "contextText": "[font-size:13px] [color:var(--color-text)] [opacity:0.8] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis] [max-width:500px]",
  "inputArea": "[padding:0_8px_8px] [background:var(--color-bg)] [flex-shrink:0] [position:relative]",
  "pendingAttachments": "[display:flex] [align-items:center] [gap:8px] [overflow-x:auto] [padding:8px] [border:1px_solid_var(--color-border)] [border-bottom:none] [border-radius:8px_8px_0_0] [background:var(--color-input-bg)]",
  "uploadStatus": "[display:inline-flex] [align-items:center] [min-height:34px] [flex:0_0_auto] [padding:0_12px] [border:1px_solid_var(--color-border)] [border-radius:999px] [background:var(--color-sidebar)] [color:var(--color-active)] [font-size:13px] [font-weight:800] [white-space:nowrap]",
  "pendingItem": "[position:relative] [width:88px] [height:88px] [flex:0_0_auto] [border:1px_solid_var(--color-border)] [border-radius:6px] [overflow:hidden]",
  "pendingThumb": "[width:100%] [height:100%] [object-fit:contain] [display:block]",
  "pendingFilePreview": "[display:flex] [width:100%] [height:100%] [flex-direction:column] [align-items:center] [justify-content:center] [gap:7px] [padding:10px_8px_8px] [box-sizing:border-box] [background:var(--color-sidebar)] [color:var(--color-text)]",
  "pendingFileIcon": "[display:inline-flex] [width:34px] [height:34px] [flex:0_0_auto] [align-items:center] [justify-content:center] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-input-bg)] [color:var(--color-active)]",
  "pendingFileName": "[width:100%] [min-width:0] [overflow:hidden] [color:var(--color-text)] [font-size:11px] [font-weight:700] [line-height:1.25] [text-align:center] [text-overflow:ellipsis] [white-space:nowrap]",
  "pendingRemove": "[position:absolute] [top:4px] [right:4px] [width:22px] [height:22px] [border:none] [border-radius:50%] [background:rgba(0,_0,_0,_0.72)] [color:#fff] [cursor:pointer] [line-height:1] [display:flex] [align-items:center] [justify-content:center] [font-size:16px]",
  "attachMenu": "[position:absolute] [left:14px] [bottom:calc(100%_+_8px)] [z-index:1200] [min-width:160px] [padding:6px] [border:1px_solid_var(--color-active)] [border-radius:8px] [background:var(--color-dropdown-bg)] [box-shadow:0_10px_28px_var(--color-dropdown-shadow)]",
  "inputBox": "[display:flex] [align-items:flex-end] [background:var(--color-input-bg)] [border-radius:8px] [border:1px_solid_var(--color-border)] [padding:6px_8px_6px_14px] [gap:8px] [transition:border-color_0.2s]",
  "fileInput": "[display:none]",
  "attachBtn": "[width:32px] [height:32px] [border:none] [border-radius:4px] [background:transparent] [color:#888] [font-size:24px] [line-height:1] [cursor:pointer] [display:flex] [align-items:center] [justify-content:center] [flex-shrink:0] [transition:background_0.15s,_color_0.15s]",
  "mainEmojiPicker": "[position:absolute] [bottom:calc(100%_+_8px)] [right:8px] [z-index:1000] [box-shadow:0_8px_24px_rgba(0,_0,_0,_0.3)] [border-radius:10px] [overflow:hidden]",
  "input": "[flex:1] [display:block] [align-self:center] [width:100%] [min-width:0] [padding:6px_0] [border:none] [background:transparent] [color:var(--color-text)] [font-size:14px] [outline:none] [resize:none] [font-family:inherit] [line-height:1.5] [min-height:33px] [max-height:160px] [overflow-y:hidden] [white-space:pre-wrap] [box-sizing:border-box]",
  "inputActions": "[display:flex] [align-items:center] [gap:2px] [flex-shrink:0] [padding-bottom:1px]",
  "inputIconBtn": "[background:none] [border:none] [cursor:pointer] [color:#888] [width:32px] [height:32px] [border-radius:4px] [display:flex] [align-items:center] [justify-content:center] [font-size:18px] [transition:color_0.15s] hover:[color:var(--color-text)]",
  "sendBtn": "[width:32px] [height:32px] [border-radius:4px] [background:var(--color-active)] [border:none] [cursor:pointer] [display:flex] [align-items:center] [justify-content:center] [flex-shrink:0] [transition:opacity_0.15s] hover:[opacity:0.85]",
  "scrollToBottom": "[position:absolute] [bottom:80px] [right:16px] [background:var(--color-bg)] [border:1px_solid_var(--color-border)] [color:var(--color-text)] [min-width:36px] [height:36px] [padding:0_12px] [border-radius:18px] [display:flex] [align-items:center] [justify-content:center] [gap:6px] [cursor:pointer] [box-shadow:0_4px_12px_rgba(0,_0,_0,_0.2)] [z-index:100] [animation:fadeIn_0.15s_ease-out] [transition:background_0.15s]",
  "scrollBadge": "[position:absolute] [top:-4px] [right:-4px] [background:var(--color-active)] [color:white] [border-radius:10px] [font-size:10px] [font-weight:700] [padding:1px_5px] [min-width:16px] [text-align:center]",
  "mention": "[color:var(--color-active)] [background:var(--color-input-focus-bg)] [padding:0_2px] [border-radius:3px] [cursor:pointer] [font-weight:500]",
  "msgGroupStart": "[margin-top:16px]",
  "warningOverlay": "[position:fixed] [inset:0] [z-index:3000] [display:flex] [align-items:center] [justify-content:center] [background:rgba(0,_0,_0,_0.45)]",
  "warningModal": "[width:min(420px,_calc(100vw_-_32px))] [border:1px_solid_var(--color-border)] [border-radius:8px] [background:var(--color-bg)] [color:var(--color-text)] [padding:20px] [box-shadow:0_16px_40px_rgba(0,_0,_0,_0.35)]",
  "chatRoomItem": "[display:flex] [align-items:center] [gap:20px] [padding:24px] [min-height:110px] [background-color:var(--color-sidebar)] [border-radius:20px] [box-shadow:0_4px_15px_rgba(0,_0,_0,_0.05)] [color:var(--color-text)] [transition:all_0.3s_ease] [border:2px_solid_var(--color-border)] [cursor:pointer] hover:[transform:translateY(-4px)] hover:[box-shadow:0_8px_25px_rgba(253,_147,_25,_0.1)] hover:[border-color:var(--color-active)]",
  "roomAvatar": "[width:70px] [height:70px] [border-radius:18px] [flex-shrink:0] [background-size:cover] [background-position:center] [overflow:hidden] [border:1px_solid_var(--color-border)]",
  "noImage": "[width:100%] [height:100%] [background:linear-gradient(135deg,_var(--color-active)_0%,_#ffb35c_100%)] [opacity:0.2]",
  "roomInfo": "[flex:1] [min-width:0] [display:flex] [flex-direction:column] [gap:4px]",
  "roomName": "[font-weight:800] [font-size:17px] [color:var(--color-text)] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis]",
  "lastMessage": "[font-size:14px] [color:var(--color-deactive)] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis] [opacity:0.8]",
  "appointmentInfo": "[display:flex] [flex-direction:column] [align-items:flex-end] [gap:4px] [min-width:120px] [flex-shrink:0]",
  "dateTime": "[font-size:14px] [font-weight:700] [color:var(--color-active)]",
  "place": "[font-size:12px] [color:var(--color-deactive)] [font-weight:500] [max-width:150px] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis]",
  "unreadBadge": "[min-width:22px] [height:22px] [padding:0_7px] [border-radius:999px] [background:#ff4757] [color:white] [font-size:12px] [font-weight:800] [line-height:22px] [text-align:center] [align-self:flex-end]",
  "kicked": "[opacity:0.6] [background-color:var(--color-input-bg)] [cursor:default] [position:relative]",
  "kickedBadge": "[display:inline-block] [margin-left:8px] [background-color:#ff4757] [color:white] [font-size:11px] [padding:2px_6px] [border-radius:4px] [font-weight:600] [vertical-align:middle]",
  "deleteBtn": "[background:var(--color-border)] [border:none] [color:var(--color-text)] [font-size:20px] [width:28px] [height:28px] [border-radius:50%] [display:flex] [align-items:center] [justify-content:center] [cursor:pointer] [opacity:0] [margin-left:10px] hover:[background-color:#ff4757] hover:[color:white]"
};
